### ISSUE TITLE
[Error: ENOENT: no such file or directory, unlink '/tmp/undefined.mp4']

### ISSUE THREAD

**Issue by ghost** [thundersquared/tikvidbot#12] opened 2020-11-10 20:08 UTC
With the newest Docker Image I only get this error Message:

[Error: ENOENT: no such file or directory, unlink '/tmp/undefined.mp4'] { errno: -2, code: 'ENOENT', syscall: 'unlink', path: '/tmp/undefined.mp4' }

**Comment by ghost** [comment] 2020-11-11 07:58
It works without Docker.

**Comment by andrusha** [comment] 2020-11-29 07:53
Still broken inside the docker

**Comment by anatolinicolae** [comment] 2020-11-29 11:41
It's caused by TikTok Scraper not being able to download the video. It's not an error but instead the result of a broken download, handled the way you see at [lines 111-119](https://github.com/thundersquared/tikvidbot/blob/master/handler/fetch.js#L111-L119). The script fails to retrieve meta at [line 95](https://github.com/thundersquared/tikvidbot/blob/master/handler/fetch.js#L95), therefore `meta.id` at [line 103](https://github.com/thundersquared/tikvidbot/blob/master/handler/fetch.js#L103) is undefined.

Unless there's an easier way to avoid or handle captchas (that's why these calls fail), I'll be closing this and stopping further development...

**Closed as completed by anatolinicolae** 2020-11-29 11:41 UTC
Labels: bug, wontfix
